export default {
  general: {
    handicap: 'Handicap',
    game: 'Game',
    stage: 'Stage',
    players: 'Players',
    raceTo: 'Race to',
    group: 'Group',
    games: {
      eight: '8-ball',
      nine: '9-ball',
      ten: '10-ball',
      straight: 'Straight pool',
    },
    yes: 'Yes',
    no: 'No',
    ndash: '–',
    ranking: 'Ranking',
    place: 'Place',
    points: 'Points',
    submit: 'Submit',
    login: 'Log in',
    logout: 'Log out',
  },
  frontPage: {
    heading: 'Welcome to Lunabrackets',
    infoheading: 'Scorekeeping tool for LaLunaLiga',
  },
  navigation: {
    seasons: 'Seasons',
    viewSeasons: 'View seasons',
    createSeason: 'Create new season',
    leagues: 'Leagues',
    createLeague: 'Create new league',
    viewLeagues: 'View leagues',
    tournaments: 'Tournaments',
    viewTournaments: 'View tournaments',
    createTournament: 'Create new tournament',
    players: 'Players',
    viewPlayers: 'View players',
  },
  season: {
    heading: 'Seasons',
    active: 'Active',
    inactive: 'Inactive',
    bonus: 'Bonus',
    sum: 'Total',
  },
  league: {
    heading: 'Leagues',
    infoText: 'League is a game mode for maximum of 32 players that consists of three stages: round-robin group stage, double elimination stage and the final single elimination stage. At first the players are\n\n' +
    'divided to 4 groups where they play against each other. Winner of each group will advance straight to the final single elimination stage and last two are eliminated from the competition.\n' +
    'The rest will move on to the double elimination stage and seeded to the bracket according to their placements. From the double elimination state 4 players will advance to the final stage and rest are eliminated. In the final stage, each group stage winner will\n' +
    'be drawn an opponent from the double-elimination stage winners.',
  },
  userForm: {
    heading: 'Create a player profile',
    infotext: 'With player profile you are able to play in tournaments and track your scores',
    firstName: 'First Name',
    lastName: 'Last Name',
    nickName: 'Nickname',
  },
  seasonForm: {
    heading: 'Create new season',
    name: 'Name',
    create: 'Create season',
  },
  seasonStatusForm: {
    heading: 'Change season status',
    activate: 'Activate',
    inactivate: 'Inactivate',
  },
  leagueForm: {
    heading: 'Create new league',
    mainFormHeading: 'Step One',
    playerHeading: 'Step Two',
    summaryHeading: 'Summary',
    formLegend: 'League',
    name: 'Name',
    game: 'Game',
    season: 'Season',
    add: 'Add',
    remove: ' Remove',
    availablePlayers: 'Available players',
    selectedPlayers: 'Selected players',
    infoCreatingLeagueHeading: 'Creating league',
    warningHeading: 'Warning',
    warningMessage: 'There are less than 32 players in the league and it will cause games with walk overs. Do you want to proceed and still create this league?',
  },
  tournamentForm: {
    heading: 'Create new tournament',
    availablePlayers: 'Available players',
    selectedPlayers: 'Selected players',
    name: 'Name',
    create: 'Create',
  },
  tournamentResults: {
    heading: 'Tournament results',
    noResults: 'No results',
  },
  leagueStartForm: {
    leagueSettings: 'League settings',
    groupNamesHeading: 'Group Names & Race to',
    raceTo: 'Race to',
    playerHandicaps: 'Player handicaps',
    startLeague: 'Start league',
  },
  endGroupStageForm: {
    heading: 'Group stage',
    matchesComplete: 'Matches complete',
    modalHeading: 'Incomplete matches',
    modalText: 'There are still incomplete group matches. Do you still want to start the qualifiers?',
    startQualifiers: 'Start qualifiers & elimination',
  },
  endQualifiersForm: {
    heading: 'Qualifiers stage',
    startFinals: 'Start finals',
  },
  endLeagueForm: {
    heading: 'Complete league',
    incompleteMatches: 'There are still matches left to be played',
    submit: 'Finish the league',
  },
  playersToFinalsForm: {
    heading: 'Select players to finals',
    lead: 'Drag & Drop to edit players',
    eligible: 'Eligible to finals',
    fromGroupStage: 'Going to finals from group stage',
    fromQualifiers: 'Going to finals from qualifiers',
  },
  leagueNavigation: {
    admin: 'Admin',
    results: 'Results',
    elimination: 'Elimination',
    group: 'Group',
    qualifiers: 'Qualifiers',
    finals: 'Finals',
  },
  adminView: {
    heading: 'Administration',
    leaguePanelHeading: 'League details',
    groupsHeading: 'Group names',
    handicapHeading: 'Adjust handicaps',
    currentStage: 'Current stage',
    start: 'Start',
    undeterminedRankingsHeading: 'Undetermined rankings',
    noUndetermined: 'No undetermined rankings',
    leagueComplete: 'This league has ended',
  },
  groupView: {
    wins: 'Wins',
    place: 'Place',
    matchScoreFormHeading: 'Enter match score',
    update: 'Update',
    groupStageNotStarted: 'Group stage has not started yet',
  },
  eliminationView: {
    bracketHeading: 'Elimination bracket',
    eliminationNotStarted: 'Mega elimination has not started yet',
  },
  qualifiersView: {
    winnerSide: 'Winner side',
    loserSide: 'Loser side',
    qualifiersNotStarted: 'Qualifiers have not started yet',
  },
  finalsView: {
    bracketHeading: 'Finals bracket',
    quarterFinals: 'Quarterfinals',
    semiFinals: 'Semifinals',
    finalsNotStarted: 'Finals have not started yet',
    final: 'Final',
  },
  resultsView: {
    heading: 'League results',
    points: 'Points',
    bonus: 'Bonus',
    total: 'Total',
    leagueNotFinished: 'League is still not finished!',
  },
  walkOverForm: {
    heading: 'Walk over',
    message: 'Walk over for',
  },
  voidForm: {
    heading: 'Void the match?',
  },
  messages: {
    leagueStart: 'League started successfully',
    matchUpdate: 'Match updated successfully',
    finalsStarted: 'Finals started successfully',
    qualifierStarted: 'Qualifiers started successfully',
    leagueFinished: 'League finished',
    creatingTournament: 'Creating tournament',
    createdTournament: 'Tournament created successfully',
    creatingTournamentResults: 'Creating tournament results',
    createdTournamentResults: 'Tournament results created successfully',
    userCreation: 'User created successfully',
  },
  errorMessages: {
    pageNotFound: 'Sorry we couldn\'t find what u were looking for...',
    leagueStart: 'Error starting league',
    finals: 'Error starting finals',
    qualifiers: 'Error startin qualifiers',
    finish: 'Error finishing the league',
    matchUpdate: 'Error updating match',
    fixSprintRankings: 'Fix rankings',
    fixRankings: 'Fix duplicate rankings',
    missingSeasonName: 'Missing season name',
    missingName: 'Missing league name',
    missingPlayers: 'Missing players',
    handicapError: 'Fix handicaps',
    invalidScore: 'Who won? Fix scores',
    tournamentCreation: 'Error creating tournament',
    tournamentResultsCreation: 'Error creating tournament results',
    userCreation: 'Error creating user',
  },
};
